coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        informational: true
    patch:
      default:
        target: 90%
        threshold: 0%
        informational: true

ignore:
  - "tests/**/*"
  - "**/*.test.ts"
  - "**/*.config.ts"
  - "dist/**/*"
  - "coverage/**/*"
  - "src/vite-env.d.ts"
  - "src/types/**/*.d.ts"

flags:
  unit:
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

github_checks:
  annotations: true
